# Unit 1 - Advance Pandas

### Conditional Formatting

In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Name": ["Aman", "Rahul", "Sneha", "Priya", "Kabir"],
    "Age": [21, 34, 19, 29, 41],
    "Score": [88, 67, 92, 74, 90],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"]
}

df = pd.DataFrame(data)
df

    Name  Age  Score     City
0   Aman   21     88    Delhi
1  Rahul   34     67   Mumbai
2  Sneha   19     92    Delhi
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [5]:
df["Age"] > 25

0    False
1     True
2    False
3     True
4     True
Name: Age, dtype: bool

In [6]:
# Extract rows where Age > 25
df[df["Age"] > 25]

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [7]:
# Multiple Conditions
# Example 1: Age > 25 AND Score > 70
df[(df["Age"] > 25) & (df["Score"] > 70)]

    Name  Age  Score     City
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [9]:
#OR
df[(df["Age"]>25) | (df["Score"]>70)]

    Name  Age  Score     City
0   Aman   21     88    Delhi
1  Rahul   34     67   Mumbai
2  Sneha   19     92    Delhi
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [12]:
# Not
df[(df['City'] != 'Delhi')]

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [10]:
df[~(df['City'] == 'Delhi')]

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [11]:
df

    Name  Age  Score     City
0   Aman   21     88    Delhi
1  Rahul   34     67   Mumbai
2  Sneha   19     92    Delhi
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [14]:
df[(df['City'] == 'Mumbai') | (df['City'] == 'Chennai')]

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [12]:
# isin() - for multiple ==
df[df['City'].isin(['Mumbai','Chennai'])]

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [13]:
# query
df.query("Age > 25 and Score<75")

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai

In [17]:
df.query("Age >25 or Score<75")

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [14]:
# query with variables
min_score = 75
df.query("Score < @min_score")

    Name  Age  Score     City
1  Rahul   34     67   Mumbai
3  Priya   29     74  Chennai

In [15]:
df

    Name  Age  Score     City
0   Aman   21     88    Delhi
1  Rahul   34     67   Mumbai
2  Sneha   19     92    Delhi
3  Priya   29     74  Chennai
4  Kabir   41     90   Mumbai

In [16]:
df['Name']

0     Aman
1    Rahul
2    Sneha
3    Priya
4    Kabir
Name: Name, dtype: str

In [17]:
df['Name'].str.contains('n')

0     True
1    False
2     True
3    False
4    False
Name: Name, dtype: bool

In [18]:
# Filter using string methods

df[df['Name'].str.contains('n')]

    Name  Age  Score   City
0   Aman   21     88  Delhi
2  Sneha   19     92  Delhi

In [19]:
df[df['Name'].str.startswith('R')]

    Name  Age  Score    City
1  Rahul   34     67  Mumbai

### MULTI-INDEXING

In [27]:
arrays = [
    ['A', 'A', 'B', 'B', 'C', 'C'],
    ['one', 'two', 'one', 'two', 'one', 'two']
]
index = pd.MultiIndex.from_arrays(arrays, names=['First', 'Second'])
df_multi = pd.DataFrame(np.random.randn(6, 2), 
                        index=index, 
                        columns=['Value1', 'Value2'])

In [28]:
df_multi

                Value1    Value2
First Second
A     one     0.636583  1.493997
      two    -1.262197  1.764980
B     one    -1.243150 -1.203041
      two     0.712759  0.901845
C     one     0.577650  1.695005
      two    -0.193782 -0.221168

In [30]:
# Create regular DataFrame
sales_data = {
    'Region': ['North', 'North', 'South', 'South', 'East', 'East'],
    'Quarter': ['Q1', 'Q2', 'Q1', 'Q2', 'Q1', 'Q2'],
    'Sales': [100, 150, 120, 180, 90, 130],
    'Profit': [20, 30, 25, 35, 15, 28]
}
df_sales = pd.DataFrame(sales_data)

# Set multiple columns as index
df_sales_multi = df_sales.set_index(['Region', 'Quarter'])
print("\nSales MultiIndex:")
df_sales_multi

Sales MultiIndex:

                Sales  Profit
Region Quarter
North  Q1         100      20
       Q2         150      30
South  Q1         120      25
       Q2         180      35
East   Q1          90      15
       Q2         130      28

In [32]:
# Create from list of tuples
tuples = [('A', 'x'), ('A', 'y'), ('B', 'x'), ('B', 'y')]
index = pd.MultiIndex.from_tuples(tuples, names=['Level1', 'Level2'])
df_tuples = pd.DataFrame(np.random.randn(4, 2), 
                         index=index, 
                         columns=['Col1', 'Col2'])
print("\nMultiIndex from tuples:")
df_tuples

MultiIndex from tuples:

                   Col1      Col2
Level1 Level2
A      x       0.246411 -1.673834
       y      -1.730767  0.402989
B      x       1.130791  0.777430
       y       0.323067  1.441584

In [33]:
# Create from cartesian product
iterables = [['A', 'B'], ['x', 'y', 'z']]
index = pd.MultiIndex.from_product(iterables, names=['First', 'Second'])
df_product = pd.DataFrame(np.random.randn(6, 2), 
                          index=index, 
                          columns=['Value1', 'Value2'])
print("\nMultiIndex from product:")
df_product

MultiIndex from product:

                Value1    Value2
First Second
A     x      -1.232824  1.259225
      y       1.001821 -0.297857
      z       0.287417 -0.537454
B     x      -0.725520 -1.044468
      y       1.358915  0.579334
      z       0.181198  0.632160

In [142]:
df_sales_multi

                Sales  Profit
Region Quarter
North  Q1         100      20
       Q2         150      30
South  Q1         120      25
       Q2         180      35
East   Q1          90      15
       Q2         130      28

In [143]:
# Select outer level
#print("\nSelect Region 'North':")
df_sales_multi.loc['North']

         Sales  Profit
Quarter
Q1         100      20
Q2         150      30

In [45]:
# Select specific combination
#print("\nSelect North, Q1:")
df_sales_multi.loc[('North', 'Q1')]

Sales     100
Profit     20
Name: (North, Q1), dtype: int64

In [145]:
# Select multiple outer levels
#print("\nSelect North and South:")
df_sales_multi.loc[['North', 'South']]

                Sales  Profit
Region Quarter
North  Q1         100      20
       Q2         150      30
South  Q1         120      25
       Q2         180      35

In [40]:
df_sales_multi.loc[[('North','Q1'), ('South','Q1')]]

                Sales  Profit
Region Quarter
North  Q1         100      20
South  Q1         120      25

#### Using .xs() - Cross Section

In [146]:
df_sales_multi

                Sales  Profit
Region Quarter
North  Q1         100      20
       Q2         150      30
South  Q1         120      25
       Q2         180      35
East   Q1          90      15
       Q2         130      28

In [47]:
# Get cross-section at a particular level
#print("\nCross-section at Q1 (level=1):")
df_sales_multi.xs('Q1', level='Quarter')

        Sales  Profit
Region
North     100      20
South     120      25
East       90      15

In [46]:
# Cross-section at North (level=0)
#print("\nCross-section at North (level=0):")
df_sales_multi.xs('North', level='Region')

         Sales  Profit
Quarter
Q1         100      20
Q2         150      30

#### Slicing MultiIndex

In [49]:
df_sales_multi.loc[[('North','Q1'),('North','Q2'),('South','Q1')]]

                Sales  Profit
Region Quarter
North  Q1         100      20
       Q2         150      30
South  Q1         120      25

In [58]:

# Using slice() for partial slicing
idx = pd.IndexSlice
#print("\nAll regions, only Q1:")
df_sales_multi.loc[idx[:, 'Q1'], :]

                Sales  Profit
Region Quarter
North  Q1         100      20
South  Q1         120      25
East   Q1          90      15

In [59]:
df_sales_multi.loc[idx[:,'Q2'],:]

                Sales  Profit
Region Quarter
North  Q2         150      30
South  Q2         180      35
East   Q2         130      28

#### Boolean Filtering on MultiIndex

In [60]:
# Filter based on values
high_sales = df_sales_multi[df_sales_multi['Sales'] > 100]
#" Sales > 100:"
high_sales

                Sales  Profit
Region Quarter
North  Q2         150      30
South  Q1         120      25
       Q2         180      35
East   Q2         130      28

In [62]:
# Combine index and value filtering
north_high = df_sales_multi.loc['North'][df_sales_multi.loc['North']['Profit'] > 25]
#north_high[df_sales_multi.loc['North']['Profit'] > 25]
#print("\nNorth region with Profit > 25:")
north_high

         Sales  Profit
Quarter
Q2         150      30

### Advanced MultiIndex Operations
#### Swapping Levels

In [64]:
# Swap index levels
swapped = df_sales_multi.swaplevel('Region', 'Quarter')
print("\nSwapped levels:")
swapped.sort_index()

Swapped levels:

                Sales  Profit
Quarter Region
Q1      East       90      15
        North     100      20
        South     120      25
Q2      East      130      28
        North     150      30
        South     180      35

In [56]:
# Sort by index
sorted_df = df_sales_multi.sort_index()
print("\nSorted by index:")
sorted_df

Sorted by index:

                Sales  Profit
Region Quarter
East   Q1          90      15
       Q2         130      28
North  Q1         100      20
       Q2         150      30
South  Q1         120      25
       Q2         180      35

In [57]:
# Sort by specific level
sorted_level = df_sales_multi.sort_index(level='Quarter')
#print("\nSorted by Quarter:")
sorted_level

                Sales  Profit
Region Quarter
East   Q1          90      15
North  Q1         100      20
South  Q1         120      25
East   Q2         130      28
North  Q2         150      30
South  Q2         180      35

# Aggregation

In [62]:
np.random.seed(42)
data = {
    'Date': pd.date_range('2023-01-01', periods=100, freq='D'),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], 100),
    'Product': np.random.choice(['Product A', 'Product B', 'Product C'], 100),
    'Category': np.random.choice(['Electronics', 'Clothing', 'Food'], 100),
    'Sales': np.random.randint(1000, 10000, 100),
    'Quantity': np.random.randint(10, 100, 100),
    'Profit': np.random.randint(100, 2000, 100)
}
df = pd.DataFrame(data)


df.head(10)

        Date Region    Product     Category  Sales  Quantity  Profit
0 2023-01-01   East  Product C     Clothing   3049        34    1303
1 2023-01-02   West  Product B     Clothing   6423        33    1346
2 2023-01-03  North  Product B         Food   5548        22     861
3 2023-01-04   East  Product B     Clothing   4108        69    1782
4 2023-01-05   East  Product B         Food   8158        16     541
5 2023-01-06   West  Product B  Electronics   8400        66    1731
6 2023-01-07  North  Product B         Food   4170        45     868
7 2023-01-08  North  Product C     Clothing   3255        54    1115
8 2023-01-09   East  Product C  Electronics   2154        29    1448
9 2023-01-10  South  Product B  Electronics   5499        74     615

In [63]:
print(f"\nDataset shape: {df.shape}")

Dataset shape: (100, 7)

### Basic GroupBy Operations
#### Single Column Grouping

In [65]:
# Group by single column and calculate mean
region_avg = df.groupby('Region')['Sales'].mean()
#print("\nAverage Sales by Region:")
print(region_avg)

Region
East     4976.791667
North    4381.300000
South    6473.576923
West     4714.400000
Name: Sales, dtype: float64

In [66]:
# Multiple aggregations on single column
region_stats = df.groupby('Region')['Sales'].agg(['mean', 'sum', 'count', 'min', 'max'])
#print("\nSales Statistics by Region:")
print(region_stats)

               mean     sum  count   min   max
Region
East    4976.791667  119443     24  1301  8683
North   4381.300000   87626     20  1154  9445
South   6473.576923  168313     26  1784  9754
West    4714.400000  141432     30  1098  9208

#### Multiple Column Grouping

In [69]:
# Group by multiple columns
product_region = df.groupby(['Region', 'Product'])['Sales'].sum()
print("\nTotal Sales by Region and Product:")
print(product_region)

Total Sales by Region and Product:
Region  Product
East    Product A    36048
        Product B    39655
        Product C    43740
North   Product A    18038
        Product B    33895
        Product C    35693
South   Product A    61584
        Product B    50765
        Product C    55964
West    Product A    59357
        Product B    18336
        Product C    63739
Name: Sales, dtype: int64

In [71]:
# Display as DataFrame instead of Series
product_region_df = df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()
print("\nAs DataFrame:")
product_region_df

As DataFrame:

   Region    Product  Sales
0    East  Product A  36048
1    East  Product B  39655
2    East  Product C  43740
3   North  Product A  18038
4   North  Product B  33895
5   North  Product C  35693
6   South  Product A  61584
7   South  Product B  50765
8   South  Product C  55964
9    West  Product A  59357
10   West  Product B  18336
11   West  Product C  63739

### Aggregation Functions
#### Using .agg() with Multiple Functions

In [72]:
# Apply multiple aggregation functions
multi_agg = df.groupby('Region').agg({
    'Sales': ['sum', 'mean', 'std'],
    'Quantity': ['sum', 'mean'],
    'Profit': ['sum', 'max', 'min']
})
print("\nMultiple Aggregations:")
multi_agg

Multiple Aggregations:

         Sales                           Quantity            Profit
           sum         mean          std      sum       mean    sum   max  min
Region
East    119443  4976.791667  2544.109462     1096  45.666667  27695  1882  111
North    87626  4381.300000  2193.942188     1034  51.700000  20023  1992  136
South   168313  6473.576923  2110.909494     1389  53.423077  27968  1965  161
West    141432  4714.400000  2643.404318     1951  65.033333  35170  1903  134

In [73]:
# Flatten column names
multi_agg.columns = ['_'.join(col).strip() for col in multi_agg.columns.values]
#print("\nWith Flattened Columns:")
multi_agg

,Sales_sum,Sales_mean,Sales_std,Quantity_sum,Quantity_mean,Profit_sum,Profit_max,Profit_min
Region,,,,,,,,
East,119443,4976.791667,2544.109462,1096,45.666667,27695,1882,111
North,87626,4381.300000,2193.942188,1034,51.700000,20023,1992,136
South,168313,6473.576923,2110.909494,1389,53.423077,27968,1965,161
West,141432,4714.400000,2643.404318,1951,65.033333,35170,1903,134

#### Custom Aggregation Functions

In [75]:
# Define custom function
def range_calc(x):
    return x.max() - x.min()

# Apply custom function
custom_agg = df.groupby('Region').agg({
    'Sales': [range_calc, 'mean'],
    'Profit': [range_calc, lambda x: x.sum() / x.count()]
})
#print("\nCustom Aggregations:")
custom_agg

            Sales                  Profit
       range_calc         mean range_calc   <lambda_0>
Region
East         7382  4976.791667       1771  1153.958333
North        8291  4381.300000       1856  1001.150000
South        7970  6473.576923       1804  1075.692308
West         8110  4714.400000       1769  1172.333333

In [76]:
# More readable syntax with named aggregations
named_agg = df.groupby('Region').agg(
    total_sales=('Sales', 'sum'),
    avg_sales=('Sales', 'mean'),
    max_profit=('Profit', 'max'),
    total_quantity=('Quantity', 'sum'),
    count=('Sales', 'count')
)
#print("\nNamed Aggregations:")
named_agg

        total_sales    avg_sales  max_profit  total_quantity  count
Region
East         119443  4976.791667        1882            1096     24
North         87626  4381.300000        1992            1034     20
South        168313  6473.576923        1965            1389     26
West         141432  4714.400000        1903            1951     30

## Advanced GroupBy Techniques
#### Iterating Through Groups

In [77]:
# Iterate through each group
print("\nIterating through groups:")
for name, group in df.groupby('Region'):
    print(f"\n{name}:")
    print(group.head(3))
    print(f"Group size: {len(group)}")

Iterating through groups:

East:
        Date Region    Product  Category  Sales  Quantity  Profit
0 2023-01-01   East  Product C  Clothing   3049        34    1303
3 2023-01-04   East  Product B  Clothing   4108        69    1782
4 2023-01-05   East  Product B      Food   8158        16     541
Group size: 24

North:
        Date Region    Product  Category  Sales  Quantity  Profit
2 2023-01-03  North  Product B      Food   5548        22     861
6 2023-01-07  North  Product B      Food   4170        45     868
7 2023-01-08  North  Product C  Clothing   3255        54    1115
Group size: 20

South:
         Date Region    Product     Category  Sales  Quantity  Profit
9  2023-01-10  South  Product B  Electronics   5499        74     615
20 2023-01-21  South  Product A  Electronics   3961        95    1787
22 2023-01-23  South  Product A  Electronics   5433        34    1798
Group size: 26

West:
         Date Region    Product     Category  Sales  Quantity  Profit
1  2023-01-02   West  Product B     Clothing   6423        33    1346
5  2023-01-06   West  Product B  Electronics   8400        66    1731
14 2023-01-15   West  Product A  Electronics   5199        96     357
Group size: 30

In [78]:
# Get a specific group
groups = df.groupby('Region')
north_data = groups.get_group('North')
print("\nNorth Region Data (first 5 rows):")
print(north_data.head())

North Region Data (first 5 rows):
         Date Region    Product     Category  Sales  Quantity  Profit
2  2023-01-03  North  Product B         Food   5548        22     861
6  2023-01-07  North  Product B         Food   4170        45     868
7  2023-01-08  North  Product C     Clothing   3255        54    1115
15 2023-01-16  North  Product B  Electronics   9445        24     596
21 2023-01-22  North  Product A     Clothing   5973        60     789

In [79]:
# Create hierarchical grouping
hierarchical = df.groupby(['Region', 'Product', 'Category'])['Sales'].sum()
print("\nHierarchical Grouping:")
print(hierarchical.head(15))

# Convert to DataFrame with unstack
unstacked = hierarchical.unstack(level='Category')
print("\nUnstacked by Category:")
print(unstacked)

Hierarchical Grouping:
Region  Product    Category
East    Product A  Clothing        6442
                   Electronics    19209
                   Food           10397
        Product B  Clothing       15435
                   Electronics    12329
                   Food           11891
        Product C  Clothing        3049
                   Electronics    22180
                   Food           18511
North   Product A  Clothing        5973
                   Electronics     6015
                   Food            6050
        Product B  Clothing        4170
                   Electronics    12286
                   Food           17439
Name: Sales, dtype: int64

Unstacked by Category:
Category          Clothing  Electronics     Food
Region Product
East   Product A    6442.0      19209.0  10397.0
       Product B   15435.0      12329.0  11891.0
       Product C    3049.0      22180.0  18511.0
North  Product A    5973.0       6015.0   6050.0
       Product B    4170.0      12286.0  17439.0
       Product C   12250.0       4987.0  18456.0
South  Product A   28635.0       9394.0  23555.0
       Product B   15915.0      14495.0  20355.0
       Product C   20629.0      14895.0  20440.0
West   Product A   27995.0      11110.0  20252.0
       Product B    9936.0       8400.0      NaN
       Product C   19837.0      27092.0  16810.0

### Filtering Groups

In [80]:
# Filter groups based on group properties
# Keep only regions with more than 20 sales records
filtered_groups = df.groupby('Region').filter(lambda x: len(x) > 20)
print(f"\nRegions with > 20 records: {filtered_groups['Region'].unique()}")
print(f"Original regions: {df['Region'].unique()}")

Regions with > 20 records: <StringArray>
['East', 'West', 'South']
Length: 3, dtype: str
Original regions: <StringArray>
['East', 'West', 'North', 'South']
Length: 4, dtype: str

In [83]:
# Keep groups where average sales > 5000
high_sales_regions = df.groupby('Region').filter(lambda x: x['Sales'].mean() > 5000)
print(f"\nRegions with avg sales > 5000:")
print(high_sales_regions.groupby('Region')['Sales'].mean())

Regions with avg sales > 5000:
Region
South    6473.576923
Name: Sales, dtype: float64

#### Transform Method

In [84]:
# Add group statistics back to original DataFrame
# Calculate z-score within each region
df['Sales_Mean_Region'] = df.groupby('Region')['Sales'].transform('mean')
df['Sales_Std_Region'] = df.groupby('Region')['Sales'].transform('std')
df['Sales_ZScore'] = (df['Sales'] - df['Sales_Mean_Region']) / df['Sales_Std_Region']


df[['Region', 'Sales', 'Sales_Mean_Region', 'Sales_ZScore']].head(10)

  Region  Sales  Sales_Mean_Region  Sales_ZScore
0   East   3049        4976.791667     -0.757747
1   West   6423        4714.400000      0.646363
2  North   5548        4381.300000      0.531782
3   East   4108        4976.791667     -0.341491
4   East   8158        4976.791667      1.250421
5   West   8400        4714.400000      1.394263
6  North   4170        4381.300000     -0.096311
7  North   3255        4381.300000     -0.513368
8   East   2154        4976.791667     -1.109540
9  South   5499        6473.576923     -0.461686

In [87]:
df

,Date,Region,Product,Category,Sales,Quantity,Profit,Sales_Mean_Region,Sales_Std_Region,Sales_ZScore
0,2023-01-01,East,Product C,Clothing,3049,34,1303,4976.791667,2544.109462,-0.757747
1,2023-01-02,West,Product B,Clothing,6423,33,1346,4714.400000,2643.404318,0.646363
2,2023-01-03,North,Product B,Food,5548,22,861,4381.300000,2193.942188,0.531782
3,2023-01-04,East,Product B,Clothing,4108,69,1782,4976.791667,2544.109462,-0.341491
4,2023-01-05,East,Product B,Food,8158,16,541,4976.791667,2544.109462,1.250421
...,...,...,...,...,...,...,...,...,...,...
95,2023-04-06,South,Product A,Clothing,6801,42,972,6473.576923,2110.909494,0.155110
96,2023-04-07,South,Product B,Food,3806,32,1921,6473.576923,2110.909494,-1.263710
97,2023-04-08,West,Product A,Food,1537,19,1396,4714.400000,2643.404318,-1.202011
98,2023-04-09,South,Product A,Clothing,6986,78,161,6473.576923,2110.909494,0.242750
99,2023-04-10,North,Product B,Electronics,2841,43,695,4381.300000,2193.942188,-0.702070

In [88]:
df.columns

Index(['Date', 'Region', 'Product', 'Category', 'Sales', 'Quantity', 'Profit',
       'Sales_Mean_Region', 'Sales_Std_Region', 'Sales_ZScore'],
      dtype='str')

In [91]:
# Apply custom function to each group
def top_sales(group):
    return group.nlargest(2, 'Sales')

# Get top 2 sales records per region
top_per_region = df.groupby('Region').apply(top_sales)
print("\nTop 2 Sales per Region:")
print(top_per_region[['Region', 'Product', 'Sales']])

Top 2 Sales per Region:

KeyError: "['Region'] not in index"

### Grouping by Time/Date

In [93]:
# Add month and quarter columns
df['Month'] = df['Date'].dt.month
df['Quarter'] = df['Date'].dt.quarter
df['Year'] = df['Date'].dt.year

# Group by time periods
monthly_sales = df.groupby('Month')['Sales'].sum()
#print("\nMonthly Sales:")
print(monthly_sales)

Month
1    165112
2    160650
3    128280
4     62772
Name: Sales, dtype: int64

In [97]:
# Using resample for time-based grouping
df_timeseries = df.set_index('Date')
weekly_sales = df_timeseries['Sales'].resample('W').sum()
print("\nWeekly Sales:")
print(weekly_sales.head())

Weekly Sales:
Date
2023-01-01     3049
2023-01-08    40062
2023-01-15    36531
2023-01-22    33826
2023-01-29    40746
Freq: W-SUN, Name: Sales, dtype: int64

In [98]:
# Group by multiple time periods
time_region = df.groupby(['Quarter', 'Region'])['Sales'].sum().unstack()
print("\nQuarterly Sales by Region:")
print(time_region)

Quarterly Sales by Region:
Region       East    North     South      West
Quarter
1        119443.0  84785.0  127575.0  122239.0
2             NaN   2841.0   40738.0   19193.0

### Size and Count Operations

In [99]:
# Count occurrences
region_counts = df.groupby('Region').size()
print("\nCount of records per Region:")
print(region_counts)

Count of records per Region:
Region
East     24
North    20
South    26
West     30
dtype: int64

In [100]:
# Count non-null values
product_counts = df.groupby('Product')['Sales'].count()
print("\nNon-null Sales count per Product:")
print(product_counts)

Non-null Sales count per Product:
Product
Product A    35
Product B    26
Product C    39
Name: Sales, dtype: int64

In [102]:
# Value counts for multiple columns
value_counts = df.groupby(['Region', 'Product']).size().reset_index(name='Count')
print("\nCombination counts:")
value_counts

Combination counts:

   Region    Product  Count
0    East  Product A      7
1    East  Product B      7
2    East  Product C     10
3   North  Product A      6
4   North  Product B      7
5   North  Product C      7
6   South  Product A      9
7   South  Product B      7
8   South  Product C     10
9    West  Product A     13
10   West  Product B      5
11   West  Product C     12

# PIVOT TABLES
Pivot tables provide a way to summarize and reorganize data, similar to Excel pivot tables.

In [105]:
# Create basic pivot table
pivot_basic = df.pivot_table(
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum'
)
#print("\nBasic Pivot Table (Sales by Region and Product):")

pivot_basic

Product  Product A  Product B  Product C
Region
East         36048      39655      43740
North        18038      33895      35693
South        61584      50765      55964
West         59357      18336      63739

### Multiple Values

In [107]:
# Pivot table with multiple value columns
pivot_multi = df.pivot_table(
    values=['Sales', 'Profit', 'Quantity'],
    index='Region',
    columns='Product',
    aggfunc='sum'
)
print("\nPivot Table with Multiple Values:")
pivot_multi

Pivot Table with Multiple Values:

           Profit                      Quantity                         Sales  \
Product Product A Product B Product C Product A Product B Product C Product A
Region
East         8028      7096     12571       334       421       341     36048
North        4957      7148      7918       340       305       389     18038
South       10091      5627     12250       470       422       497     61584
West        15061      5637     14472       859       301       791     59357


Product Product B Product C
Region
East        39655     43740
North       33895     35693
South       50765     55964
West        18336     63739

### Multiple Aggregation Functions

In [108]:
# Apply different functions to different columns
pivot_mixed = df.pivot_table(
    values=['Sales', 'Quantity'],
    index='Region',
    columns='Product',
    aggfunc={
        'Sales': ['sum', 'mean'],
        'Quantity': ['sum', 'max']
    }
)
print("\nPivot Table with Multiple Aggregation Functions:")
pivot_mixed

Pivot Table with Multiple Aggregation Functions:

         Quantity                                                    \
              max                           sum
Product Product A Product B Product C Product A Product B Product C
Region
East           85        95        71       334       421       341
North          99        72        98       340       305       389
South          95        94        76       470       422       497
West           96        96        99       859       301       791

               Sales
                mean                                 sum
Product    Product A    Product B    Product C Product A Product B Product C
Region
East     5149.714286  5665.000000  4374.000000     36048     39655     43740
North    3006.333333  4842.142857  5099.000000     18038     33895     35693
South    6842.666667  7252.142857  5596.400000     61584     50765     55964
West     4565.923077  3667.200000  5311.583333     59357     18336     63739

### Multiple Index/Column Levels

In [110]:
# Hierarchical pivot table
pivot_hierarchical = df.pivot_table(
    values='Sales',
    index=['Region', 'Category'],
    columns=['Product', 'Quarter'],
    aggfunc='sum',
    fill_value=0
)
print("\nHierarchical Pivot Table:")
pivot_hierarchical.head(10)

Hierarchical Pivot Table:

Product            Product A        Product B        Product C
Quarter                    1      2         1      2         1     2
Region Category
East   Clothing         6442      0     15435      0      3049     0
       Electronics     19209      0     12329      0     22180     0
       Food            10397      0     11891      0     18511     0
North  Clothing         5973      0      4170      0     12250     0
       Electronics      6015      0      9445   2841      4987     0
       Food             6050      0     17439      0     18456     0
South  Clothing        14848  13787      9319   6596     20629     0
       Electronics      9394      0     14495      0     14895     0
       Food            23555      0         0  20355     20440     0
West   Clothing        27995      0      9936      0     11277  8560

#### Fill Missing Values

In [112]:
# Handle missing values in pivot table
pivot_filled = df.pivot_table(
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc='sum',
    fill_value=0  # Replace NaN with 0
)
print("\nPivot Table with Filled Values:")
pivot_filled

Pivot Table with Filled Values:

Product  Product A  Product B  Product C
Region
East         36048      39655      43740
North        18038      33895      35693
South        61584      50765      55964
West         59357      18336      63739

# Advanced Pivot Table Operations
#### Using Custom Aggregation Functions

In [114]:
# Custom aggregation in pivot table
def revenue_range(x):
    return x.max() - x.min()

pivot_custom = df.pivot_table(
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc=[revenue_range, 'mean', 'count']
)
print("\nPivot Table with Custom Function:")
pivot_custom

Pivot Table with Custom Function:

        revenue_range                             mean               \
Product     Product A Product B Product C    Product A    Product B
Region
East             7382      6031      6640  5149.714286  5665.000000
North            4819      6604      6475  3006.333333  4842.142857
South            5793      5513      7022  6842.666667  7252.142857
West             7513      7302      7639  4565.923077  3667.200000

                         count
Product    Product C Product A Product B Product C
Region
East     4374.000000         7         7        10
North    5099.000000         6         7         7
South    5596.400000         9         7        10
West     5311.583333        13         5        12

### Observed Parameter (for Categorical Data)

In [116]:
# Convert to categorical
df['Region_Cat'] = pd.Categorical(df['Region'])
df['Product_Cat'] = pd.Categorical(df['Product'])

# Use observed=True to only show existing categories
pivot_observed = df.pivot_table(
    values='Sales',
    index='Region_Cat',
    columns='Product_Cat',
    aggfunc='sum',
    observed=True  # Only show observed category combinations
)
# print("\nPivot Table with Observed Categories:")
pivot_observed

Product_Cat  Product A  Product B  Product C
Region_Cat
East             36048      39655      43740
North            18038      33895      35693
South            61584      50765      55964
West             59357      18336      63739

### Crosstab (Special Case of Pivot Table)

In [117]:
# Crosstab for frequency tables
crosstab_basic = pd.crosstab(
    df['Region'],
    df['Product']
)
print("\nCrosstab - Frequency Count:")
crosstab_basic

Crosstab - Frequency Count:

Product  Product A  Product B  Product C
Region
East             7          7         10
North            6          7          7
South            9          7         10
West            13          5         12

In [118]:
# Crosstab with values
crosstab_values = pd.crosstab(
    df['Region'],
    df['Product'],
    values=df['Sales'],
    aggfunc='sum'
)
#print("\nCrosstab with Sales Values:")
crosstab_values

Product  Product A  Product B  Product C
Region
East         36048      39655      43740
North        18038      33895      35693
South        61584      50765      55964
West         59357      18336      63739

In [119]:
# Crosstab with margins and percentages
crosstab_margins = pd.crosstab(
    df['Region'],
    df['Product'],
    margins=True,
    normalize='all'  # Can be 'all', 'index', or 'columns'
)
#print("\nCrosstab with Normalized Values:")
crosstab_margins

Product  Product A  Product B  Product C   All
Region
East          0.07       0.07       0.10  0.24
North         0.06       0.07       0.07  0.20
South         0.09       0.07       0.10  0.26
West          0.13       0.05       0.12  0.30
All           0.35       0.26       0.39  1.00